apiVersion: v1
data:
  proxy-connect-timeout: {{ .Values.proxyConnectTimeout | quote }}
  proxy-read-timeout: {{ .Values.proxyReadTimeout | quote }}
  proxy-send-timeout: {{ .Values.proxySendTimeout | quote }}
  proxy-body-size: {{ .Values.proxyBodySize | quote }}
  server-name-hash-bucket-size: {{ .Values.serverNameHashBucketSize | quote }}
  hsts-preload: {{ .Values.hstsPreload | quote }}
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
