apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-d
  namespace: wp-{{ .Values.name }}
  labels:
    app: wp-{{ .Values.name }}
data:
{{ (.Files.Glob "nginx/conf.d/*").AsConfig | indent 2 }}
