apiVersion: v1
kind: Service
metadata:
  name: wp-{{ .Values.name }}
  namespace: wp-{{ .Values.name }}
  labels:
    app: wp-{{ .Values.name }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: wp-{{ .Values.name }}
    tier: frontend
  type: ClusterIP
